"""users table

Revision ID: fe84cb9cdfef
Revises: 
Create Date: 2019-10-16 08:58:18.671232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe84cb9cdfef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('USER_NAME', sa.String(length=64), nullable=True),
    sa.Column('USER_EMAIL', sa.String(length=120), nullable=True),
    sa.Column('USER_PASSWORD', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('USER_ID')
    )
    op.create_index(op.f('ix_user_USER_EMAIL'), 'user', ['USER_EMAIL'], unique=True)
    op.create_index(op.f('ix_user_USER_NAME'), 'user', ['USER_NAME'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_USER_NAME'), table_name='user')
    op.drop_index(op.f('ix_user_USER_EMAIL'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
